{{- if .Values.catalogDb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: catalog-db-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "retail-store.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.catalogDb.password | quote }}
{{- end }}

{{- if .Values.ordersDb.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: orders-db-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "retail-store.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.ordersDb.password | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.password | quote }}
{{- end }}
